version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.0.0
    commands:
    - echo "No installation required, just copying project files."
  pre_build:
    commands:
    - npm test
  build:
    commands:
    - echo "No build step required."
  post_build:
    commands:
    - echo "Removing unwanted files..."
    - rm -f .gitignore README.md
    - echo "Preparing to package artifacts for deployment..."

artifacts:
  files:
  - 'appspec.yml'
  - 'scripts/*'
  - '**/*'
  - '!**/.gitignore'
  - '!**/README.md'
  discard-paths: yes
