version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/srv
hooks:
  BeforeInstall:
  - location: before_install.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: after_install.sh
    timeout: 300
    runas: root

  ApplicationStart:
  - location: start.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: stop.sh
    timeout: 300
    runas: root



